---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tomcat
      version: blue
  template:
    metadata:
      name: tomcat
      labels:
        app: tomcat
        version: blue
    spec:
      containers:
      - name: tomcat
        image: hello-world/tomcat:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata:
  name: tomcat
  labels:
    app: tomcat
spec:
  selector:
    app: tomcat
    version: blue
  type: NodePort
  ports:
  - nodePort: 31113
    port: 80
    targetPort: 80
